name: tests-mollysclub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for any changes to auth folder/service
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up the Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B test

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'commit badge'
          add: '*.svg'

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/
# jobs:
#   # This workflow contains a single job called "build"
#   test:
#     name: Unit Test
#     runs-on: ubuntu-18.04

#     steps:
#       - uses: actions/checkout@v1
#       - name: Set up JDK 11
#         uses: actions/setup-java@v1
#         with:
#           java-version: 1.11
#       - name: Maven Package
#         run: mvn -B clean package -DskipTests
#       # - name: Maven Verify
#       #   run: mvn -B clean verify
#       - name: Maven Build
#         run: mvn -B test
#       - name: Generate JaCoCo Badge
#         uses: cicirello/jacoco-badge-generator@v2
#         with:
#           jacoco-csv-file: target/site/jacoco/jacoco.csv
#           badges-directory: .github/badges
#           generate-coverage-badge: true
#           coverage-badge-filename: jacoco.svg
#           generate-branches-badge: true
#           branches-badge-filename: branches.svg
#           generate-coverage-endpoint: false
#           coverage-endpoint-filename: jacoco.json
#           generate-branches-endpoint: false
#           branches-endpoint-filename: branches.json
#           colors: '#4c1 #97ca00 #a4a61d #dfb317 #fe7d37 #e05d44'
#           intervals: 100 90 80 70 60 0
#           on-missing-report: fail
#           fail-if-coverage-less-than: 0
#           fail-if-branches-less-than: 0
#           fail-on-coverage-decrease: false
#           fail-on-branches-decrease: false
